- hosts: es-filebeat-nodes
  tasks:
    - name: create cert dirs
      file:
        path: /etc/pki/certs
        state: directory
      sudo: yes
    - name: copy client certificates
      copy:
        src: certs/client-ca.cer
        dest: /etc/pki/certs
      sudo: yes
    - name: copy client certificates
      copy:
        src: certs/client.cer
        dest: /etc/pki/certs
      sudo: yes
    - name: copy client certificates
      copy:
        src: certs/client.key
        dest: /etc/pki/certs
      sudo: yes
    - name: prepare datasets
      shell: |
        mkdir -p /home/vagrant/datasets
        tar xfvz /vagrant/datasets/elastic_blog_curated_access_logs.tar.gz -C /home/vagrant/datasets

- name: install filebeat on specified hosts
  hosts: es-filebeat-nodes,es-master-nodes
  roles:
    - { name: elastic.beats, beat: "filebeat", when: "'es-filebeat-nodes' in group_names",
        beat_conf: {
          "filebeat.inputs": [
            { "type": "log",
              "close_inactive": "10m",
              "enabled": true,
              "paths": [ "/home/vagrant/datasets/elastic_blog_curated_access_logs_server*/*.log" ]
          } ],
          "processors": [
            { "decode_json_fields":
              { "target": "",
                "fields": ["message"],
                "overwrite_keys": true
              }
            },
            { "drop_fields":
              { "fields": ["message", "prospector", "beat", "source", "offset"]
              }
          } ],
          "setup.template": {
            "enabled": false
          },
          "setup.ilm": {
            "enabled": false
          }
        },
        output_conf: {
          "elasticsearch": {
            "hosts": "{{el_instance_http_url}}",
            "ssl.verification_mode": "full",
            "index": "logs_%{[host]}",
            "bulk_max_size": "1000",
            "username": "elastic",
            "password": "{{elastic_password}}",
            "ssl.certificate_authorities": ["/etc/pki/certs/client-ca.cer"]
          }
        }
    }
  sudo: yes 
  vars:
    beats_version: "{{elk_version}}"
    use_repository: "{{es_use_repository}}"
    custom_package_url: "{{filebeat_custom_package_url}}"
    elastic_password: ""

